[FEAT] 회원 탈퇴 API
Katchup-dev/Katchup-server pull request #157
Opened 2023-10-15 13:55 UTC by Seokyeong237

## 📝 Summary

회원 탈퇴 API를 구현하였습니다.

## 👩‍💻 Contents

- 회원탈퇴 시, 탈퇴 사유를 withdraw 테이블에 저장합니다.
- 회원탈퇴 시, 해당 회원이 쓴 인수인계 기록을 모두 softdelete 합니다.
- 기획 측의 요청에 따라 회원탈퇴 날로부터 몇 일이 지났는지를 계산하기 위해 withdraw 테이블에 deletedAt 필드를 추가하였습니다. (@CreatedDate 이지만 필드명만 deletedAt 입니다. 직관성을 위해)
- 회원탈퇴 후 재로그인 시, isNewUser=True, isDeleted=False 로 값을 변경합니다.
- 다음 스프린트에서 회원탈퇴 후 60일이 지나면 실제 기록을 삭제하는 로직이 추가되어야 합니다.
![회탈](https://github.com/Katchup-dev/Katchup-server/assets/64405757/3dd3571f-5fd5-4d9a-a51c-1ef0017de4ed)

## 📝 Review Note

## 📣 Related Issue

- close #

## 📬 Reference

2023-10-16 09:03 UTC, unanchoi requested changes
수고하셨습니다!!

member에서 soft delete가 적용되었기 떄문에 member 조회하는 로직에서 deleted 여부도 추가된 형태로 조회를 해야할 것 같네요!!

2023-10-16 09:03 UTC, unanchoi commented on src/main/java/site/katchup/katchupserver/api/member/domain/Withdraw.java
> +    @Column(nullable = false, length = 2000)
`columnDefinition` 옵션에 "TEXT" 로 선언해도 괜찮을 것 같아요~!

2023-10-16 09:03 UTC, unanchoi commented on src/main/java/site/katchup/katchupserver/api/member/domain/Withdraw.java
> +        this.deletedAt = now();
deletedAt에 삭제할 날
즉, 현재 시간에 60을 더해서 저장해두는 것이 이후에 삭제 로직을 추가할 떄 좋을 것 같아요!!

2023-10-16 09:07 UTC, Seokyeong237 commented on src/main/java/site/katchup/katchupserver/api/member/domain/Withdraw.java
> +    @Column(nullable = false, length = 2000)
기획측 길이 제한이 2000자라 일부러 랜덤인 TEXT를 안쓰고 저렇게 선언했는데 , 특별한 이유가 있을까요!?

2023-10-16 12:47 UTC, yeseul106 approved these changes
고생하셨습니다 ~!

2023-10-16 12:51 UTC, yeseul106 commented on src/main/java/site/katchup/katchupserver/api/member/domain/Withdraw.java
> +        this.deletedAt = now().plusDays(60);
개인적인 생각으로는 60일 뒤까지 저장해서 관리할 거면 필드명이 좀 더 직관적이었으면 좋겠어요 !
deletedAt은 탈퇴한 시점이라는 이해가 더 먼저일것 같아서 ! "retentionDate"와 같은 탈퇴 이후 60일 동안 보존 가능한 데드라인의 의미가 있으면 좋겠는데,, 이건 제 개인적인 생각이기도 해서 ! 다른 분들 생각도 궁금합니다 ~

2023-10-16 13:02 UTC, Seokyeong237 commented on src/main/java/site/katchup/katchupserver/api/member/domain/Withdraw.java
> +        this.deletedAt = now().plusDays(60);
음 그럼 현재 저장된 날짜는 예상 삭제 날짜니까 expectedDeleteAt 이 좋을 것 같은데 좀 길지만 괜찮은 것 같으면 변경하겠습니다!

2023-10-16 13:03 UTC, yeseul106 commented on src/main/java/site/katchup/katchupserver/api/member/domain/Withdraw.java
> +        this.deletedAt = now().plusDays(60);
넵 좋은 것 같습니다 !!

2023-10-16 16:01 UTC, unanchoi commented on src/main/java/site/katchup/katchupserver/api/member/domain/Withdraw.java
> +    @Column(nullable = false, length = 2000)
그러면 2000자 제한으로 가도 될 것 같네요...!

2023-10-17 06:10 UTC, unanchoi approved these changes
고생하셨슴다

2023-10-17 06:51 UTC, merged