[REFACTOR] 프로필 정보 설정 API 리팩토링
Katchup-dev/Katchup-server pull request #184
Opened 2023-10-26 15:48 UTC by unanchoi

## 📝 Summary

요구사항에 맞춰서 프로필 정보 설정 API를 리팩토링 했습니다.

## 👩‍💻 Contents

1. 프로필 정보 조회 시에 한줄 소개도 조회할 수 있도록 Response에 필드를 추가했습니다.
2. 프로필 정보 수정 API에서 validator에서 제공하는 어노테이션을 활용하여, Validation 할 수 있는 로직을 추가했습니다.
3. 프로필 정보 수정 시에 이미지 확장자와 사이즈를 검증할 수 있도록 로직을 추가했습니다.

## 📝 Review Note

## 📣 Related Issue

- close #179

2023-10-26 16:47 UTC, yeseul106 requested changes
고생하셨습니다 ! 리뷰 남겼어요 !!

2023-10-26 16:47 UTC, yeseul106 commented on src/main/java/site/katchup/katchupserver/api/member/service/Impl/MemberServiceImpl.java
>      private static final String PROFILE_IMAGE_PREFIX = "profiles";
p5;

파일이랑 스크린샷에서 각각 s3의 디렉터리명을 나타내는 상수명이 `SCREENSHOT_FOLDER_NAME`, `FILE_FOLDER_NAME` 이라서 프로필 이미지 디렉터리도 통일 하는게 더 좋을 것 같긴 합니다 ! PREFIX로 하던지, FOLDER_NAME으로 하던지..?

2023-10-26 16:47 UTC, yeseul106 commented on src/main/java/site/katchup/katchupserver/common/response/ErrorCode.java
> +    PROFILE_IMAGE_SIZE_EXCEED("KC-108"),
p2;

`KC-108`이라는 에러 코드가 현재 노션에 없는 것 같은데, 한번 확인 부탁드립니다 !

2023-10-26 16:47 UTC, yeseul106 commented on src/main/java/site/katchup/katchupserver/common/response/ErrorCode.java
> +    INVALID_MEMBER_INTRODUCTION("MP-103"),
p3;

저번에 에러코드 규칙 정할 때, 앞에 문자는 도메인을 나타내서 식별하기 쉽도록 하고 뒤에 붙는 숫자는 만들기에 헷갈리지 않게 1씩 그냥 증가하기로 했던 것 같은데,,,! 

MP는 100부터 시작하도록 구현하신 이유가 따로 있을까요 ??

2023-10-26 16:49 UTC, unanchoi commented on src/main/java/site/katchup/katchupserver/common/response/ErrorCode.java
> +    INVALID_MEMBER_INTRODUCTION("MP-103"),
놓친 부분이네요 수정하겠습니다!

2023-10-26 16:50 UTC, unanchoi commented on src/main/java/site/katchup/katchupserver/common/response/ErrorCode.java
> +    PROFILE_IMAGE_SIZE_EXCEED("KC-108"),
잘못 표기했네요. 수정 하겠습니다!

2023-10-26 16:50 UTC, unanchoi commented on src/main/java/site/katchup/katchupserver/api/member/service/Impl/MemberServiceImpl.java
>      private static final String PROFILE_IMAGE_PREFIX = "profiles";
통일 하겠습니다!

2023-10-26 19:02 UTC, Seokyeong237 approved these changes
수고하셨습니다~!

2023-10-29 15:06 UTC, yeseul106 requested changes
모두 잘 반영해주신 것 확인했습니다 ! 다만, `PROFILE_IMAGE_SIZE_EXCEED`이 `KC-108`로 되어있는 것만 한번 더 확인 해주시면 될 것 같습니다 !

2023-10-29 15:17 UTC, yeseul106 approved these changes
고생 많으셨습니다 !! 최고 ..!

2023-10-29 15:17 UTC, merged