#2 [FEAT] Entity 개발
Katchup-dev/Katchup-server pull request #9
Opened 2023-05-12 08:24 UTC by yeseul106

## 📝 Summary

- Entity 개발 완료 했습니다 !

## 👩‍💻 Contents

- Entity 생성은 빌더 패턴 이용했습니다.

    - 정적 팩토리 메소드 패턴과 고민하다가, Entity가 가지는 필드의 개수도 많고 optional 적인 필드도 많은 것 같아 빌더 패턴이 더 적당한 듯 판단하여 모든 Entity의 생성 패턴은 빌더로 통일 했습니다.

- 단방향 매핑은 모두 해놓은 상태이고, 제가 그냥 설계하면서 판단했을 때 양방향 매핑으로 리스트가 있으면 편할 것 같은 엔티티들은 양방향 매핑 진행했습니다. 추후 각자 맡은 api 개발하면서 양방향 필요하면 각자 판단 해서 추가하는 게 좋을 것 같아요!

- Test 코드는 Member와 Card만 작성해서 진행 해봤습니다.
![image](https://github.com/Katchup-dev/Katchup-server/assets/68415644/a0e9fd4b-605d-4cc9-859c-b1e0448a5404)
![image](https://github.com/Katchup-dev/Katchup-server/assets/68415644/10710fc1-b4a5-43f3-8765-0d8f57f35b6e)

## 📝 Review Note

- 스프링이 어려운 이유... 고민해보고 결정할 기로가 많다...
- 효율적이고 올바른 엔티티 설계를 고민하다보니 시간이 오래 걸렸던 것 같아요 ! 이점 죄송합니다 🥲
- 그리고 보다보면 제가 실수한 부분 있을거에요 ... 검토 부탁 드려요....ㅎㅎㅎ

## 📣 Related Issue

- close #2 

## 📬 Reference

2023-05-12 08:36 UTC, unanchoi requested changes
고생 매우 많으셨습니다! Review 해둔 것 확인 부탁드려요~!

2023-05-12 08:36 UTC, unanchoi commented on src/main/java/site/katchup/katchupserver/api/TaskKeyword/domain/TaskKeyword.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
p4;

static으로 빼서
`AccessLevel.PROTECTED`로  조금 더 깔끔하게 관리하는 것도 좋을 것 같습니다!

2023-05-12 08:36 UTC, unanchoi commented on src/main/java/site/katchup/katchupserver/api/TaskKeyword/domain/TaskKeyword.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
p4;

static으로 빼서
`GenerationType.IDENTITY`로 조금 더 깔끔하게 관리하는 것도 좋을 것 같습니다!

2023-05-12 08:36 UTC, unanchoi commented on src/main/java/site/katchup/katchupserver/api/TaskKeyword/domain/TaskKeyword.java
> +    private Keyword keyword;
p4; 

여기는 LAZY 설정을 왜 안했는지 궁금합니다.

2023-05-12 08:36 UTC, unanchoi commented on src/main/java/site/katchup/katchupserver/api/member/domain/Member.java
> +    @Id
p4; 

한 줄 띄어쓰기 해서 통일성 맞추면 좋을 것 같습니다

2023-05-12 08:36 UTC, unanchoi commented on src/main/java/site/katchup/katchupserver/common/domain/BaseEntity.java
> +@MappedSuperclass
p4;

다른 Entity annotation 방식과 비슷하게 `@Getter`를 아래로 빼줘도 좋을 것 같습니다!

2023-05-12 08:36 UTC, unanchoi commented on src/main/java/site/katchup/katchupserver/api/member/domain/Member.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
p3;

Member에는 `@Getter`가 없는 이유가 있을까요? Member도 Getter가 필요할 것 같습니다!

2023-05-12 08:36 UTC, unanchoi commented on src/main/java/site/katchup/katchupserver/common/domain/BaseEntity.java
> +    private LocalDateTime modifiedAt;
p2;

DB에 snake case로 들어갈려면 다른 Entity에 해두신 것 처럼
`@Column("created_at")`이 필요할 것 같습니다!

2023-05-12 08:48 UTC, Seokyeong237 commented on src/main/java/site/katchup/katchupserver/api/card/domain/Card.java
> +
p5;

요 줄 삭제부탁드립니다 하하하

2023-05-12 08:48 UTC, Seokyeong237 commented on src/main/java/site/katchup/katchupserver/api/card/domain/Card.java
> +    @Column
p3; 

최대 글자수가 2000자이니까 @Size(max=2000) 나 @Column (length=2000) 으로 검증해주면 좋을 것 같습니다!

2023-05-12 08:48 UTC, Seokyeong237 commented on src/main/java/site/katchup/katchupserver/api/card/domain/Card.java
> +    @Column
p3;

비고도 최대 글자수 200자네요!

2023-05-12 08:48 UTC, Seokyeong237 commented on src/main/java/site/katchup/katchupserver/api/card/domain/Card.java
> +    public void addFile(File file) {
p5;

한 줄 띄어쓰기 부탁드립니다!!

2023-05-12 08:48 UTC, Seokyeong237 commented on src/main/java/site/katchup/katchupserver/api/member/domain/Member.java
> +    @Column(nullable = false)
p3;

닉네임 최대글자수 20이네요!

2023-05-12 08:50 UTC, Seokyeong237 requested changes
너무너무 수고많으셨어요 👍👍👍🍭

2023-05-12 08:52 UTC, unanchoi requested changes

2023-05-12 08:52 UTC, unanchoi commented on src/main/java/site/katchup/katchupserver/api/screenshot/domain/Screenshot.java
> +    private Long id;
p3;

type Long에서 UUID로 변경 부탁드려요!

2023-05-12 08:56 UTC, unanchoi requested changes

2023-05-12 08:56 UTC, unanchoi commented on src/main/java/site/katchup/katchupserver/KatchupserverApplication.java
> +@EnableJpaAuditing
p3;

main class에는 최대한 깔끔하게 관리되는 게 좋을 것 같아서, 따로 JpaAuditingConfig class를 만들어도 좋을 것 같아요!

2023-05-12 08:59 UTC, unanchoi commented on src/main/java/site/katchup/katchupserver/KatchupserverApplication.java
> +@EnableJpaAuditing
```Java
@EnableJpaAuditing
@Configuration
public class JpaConfig {
}
```

2023-05-12 13:47 UTC, yeseul106 commented on src/main/java/site/katchup/katchupserver/api/TaskKeyword/domain/TaskKeyword.java
> +    private Keyword keyword;
죄송해요 놓쳤네요 ! ㅜㅜㅜ 수정 하겠습니다 ~~

2023-05-12 13:48 UTC, yeseul106 commented on src/main/java/site/katchup/katchupserver/common/domain/BaseEntity.java
> +    private LocalDateTime modifiedAt;
넵 수정하겠습니다 ~~

2023-05-12 13:49 UTC, yeseul106 commented on src/main/java/site/katchup/katchupserver/api/card/domain/Card.java
> +    @Column
넵 좋아요 ! 디테일적인걸 잡지를 못했네용 ㅠㅠ 수정하겠습니다 !

2023-05-12 19:48 UTC, yeseul106 commented on src/main/java/site/katchup/katchupserver/api/card/domain/Card.java
> +    @Column
아 저 생각났어요 !! 이거랑 위에꺼 같이 엔티티 필드에서도 제약 걸지 않았던 이유는 Dto에서 거는 것이 맞다고 생각했기 때문이었습니다.

엔티티의 제약 조건은 데이터베이스 스키마에만 영향을 미쳐서 엔티티 객체를 생성하거나 업데이트할 때, 이러한 제약 조건은 적용되지 않을 수 있다고 합니다. 그리고 추후 변경될 가능성이 있다고 생각해서 dto단에서 거는게 맞다고 생각했는데..! 엔티티 필드에서도 걸고 Dto에서도 거는게 일관성 면에서 좋을것 같네용 !! 수정하겠습니다앗

2023-05-13 02:37 UTC, unanchoi approved these changes
수고 많으셨습니다 ㅎ

2023-05-13 03:51 UTC, Seokyeong237 approved these changes
수고하셨습니다 ::))))

2023-05-13 05:56 UTC, merged